name: Build on macOS

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Clone git repository ${{ github.event.workflow_run.head_branch }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: true
      - name: Setup macOS Environment
        run: |
          brew update
          brew upgrade
          brew install libopenmpt portaudio fftw qt cmake ninja create-dmg coreutils

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ./build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ./build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Deploy
        run: |
            echo "⚠️ Please ignore the errors of macdeployqt below. The errors will be fixed by the next command macdeployqtfix."
            macdeployqt ./build/ModPlug\ Player.app
            python ./DeploymentScripts/macdeployqtfix.py ./build/ModPlug\ Player.app/Contents/MacOS/ModPlug\ Player $(dirname $(dirname $(grealpath /usr/local/bin/macdeployqt)))
            create-dmg \
              --volname "ModPlug Player Installer" \
              --volicon "Installers/DMG/MPP Disk Icon.icns" \
              --background "Installers/DMG/MPP Installer Background.png" \
              --window-pos 200 120 \
              --window-size 600 420 \
              --icon-size 128 \
              --icon "ModPlug Player.app" 148 185 \
              --hide-extension "ModPlug Player.app" \
              --app-drop-link 455 184 \
              "ModPlug Player for macOS.dmg" \
              ./build/ModPlug\ Player.app

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./ModPlug\ Player\ for\ macOS.dmg
          tag_name: ${{ github.event.workflow_run.head_branch }}
